### PR TITLE
Add missing bindings in case of the t-f-j rotation

### PR DESCRIPTION
**Pull request by timacs**
Finally, this PR adds all currently missing bindings, excluding the window commands. The first two commits are straightforward, while the last one is moot.

### CODE REVIEW

**Comment by timacs** [comment]
Oops, I inadvertently pushed a commit that was intended for a separate PR, consisting of that commit only. Do you mind leaving it here and letting this PR be home for both the new t-f-j bindings and the improved Vim plugin?

**Comment by wbolster** [comment]
as usual, top quality changes 👍🏼

i merged (well, cherry-picked) these changes:

- ddea448 Improve the Vim version of this package
- b4dfb00 Add t-f-j bindings for switching tabs
- 4340580 Add a key binding for evil-find-file-at-point-visual

i did not pick the commit titled

> Add a t-f-j binding "zj" to scroll the cursor line to top

… because it is not clear to me why this is useful:

- evil also has `evil-scroll-line-to-center` and `evil-scroll-line-to-bottom`, but this change only binds `evil-scroll-line-to-top`
- emacs already has `recenter-top-bottom` which seems to do the same but better: repeated invocations cycle through all variations: center, top, bottom. (i personally have it mapped to `ctrl-L` because it reminds me of `ctrl-L` in terminals to clear the screen by scrolling)

anything i'm missing here?

**Comment by timacs** [comment]
I wanted the `zj` binding for consistency with the Vim plugin, but I agree that it seems premature in Evil. It breaks mnemonics (scroll to Top), and—as you noted—Emacs has a better alternative. I think we may leave it alone for now.

**Comment by timacs** [comment]
Assigning to you just in case you wanted something else.

**Comment by wbolster** [comment]
agree 👍🏼  exact vim compatibility is not a primary goal of this package. existing emacs facilities are just fine here.

we could bind `zj` to `recenter-top-bottom` and ignore `evil-scroll-line-to-*`, but for me it doesn't add much value. what do you think?

**Comment by timacs** [comment]
I agree with you – it's not worth maintenance. While it might make sense in Vim, the Emacs package should not mirror all Vim quirks.

**Comment by wbolster** [comment]
ok, closing because the remainder of this pull request is merged already:

- ddea448 Improve the Vim version of this package
- b4dfb00 Add t-f-j bindings for switching tabs
- 4340580 Add a key binding for evil-find-file-at-point-visual

**Pull request closed without merging**
